config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import UserLogoutView, UserLoginView, RegisterView, verification, UserUpdateView, get_users_list

app_name = UsersConfig.name

urlpatterns = [
    path('', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),
    path('verify_message/', TemplateView.as_view(template_name='users/verify_message.html'), name='verify_message'),
    path('email/verify/<str:verify_code>', verification, name='verify'),
    path('success_verify/', TemplateView.as_view(template_name='users/success_verify.html'), name='success_verify'),
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'), name='invalid_verify'),
    path('users_list/', get_users_list, name='list_view'),
    path('edit/<int:pk>', UserUpdateView.as_view(), name='edit')
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render

# Create your views here.

users/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="en">


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SendMailService</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>

<style>
    body {
        background: url('static/images/bkg.png');
        background-position: center;
        background-attachment: fixed;
        background-size; cover;
        font-family: 'Lato', sans-serif;
    }
    .card {
background-color: rgba(255, 255, 255, 0.1);
    }
    .container {
        padding: 50px 16px;
    }
    button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
        font-size: 18px;
    }

    button:hover, a:hover {
        opacity: 0.7;
    }
    .title {
        color: rgba(83, 149, 189, 0.7);
        font-size: 30px;
    }
    a {
        text-decoration: none;
        font-size: 22px;
        color: black;
    }
    .topnav {
        overflow: hidden;
        background-color: #333;
    }

    .topnav a {
        float: right;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
    }

    .topnav a:hover {
        background-color: #ddd;
        color: black;
    }

    .topnav a.active {
        background-color: #4CAF50;
        color: white;
    }
.overlay {
    height: 100%;
    width: 0;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: rgb(0,0,0);
    background-color: rgba(0,0,0, 0.9);
    overflow-x: hidden;
    transition: 0.5s;
}

.overlay-content {
    position: relative;
    top: 25%;
    width: 100%;
    text-align: center;
    margin-top: 30px;
}

.overlay a {
    padding: 8px;
    text-decoration: none;
    font-size: 36px;
    color: #818181;
    display: block;
    transition: 0.3s;
}

.overlay a:hover, .overlay a:focus {
    color: #f1f1f1;
}

.overlay .closebtn {
    position: absolute;
    top: 20px;
    left: 45px;
    font-size: 60px;
}

@media screen and (max-height: 450px) {
  .overlay a {font-size: 20px}
  .overlay .closebtn {
    font-size: 40px;
    top: 15px;
    right: 35px;
  }
}

.header {
  overflow: hidden;
  background-color: rgba(255, 255, 255, 0.0);
  padding: 20px 10px;
}

.header a {
  float: left;
  color: black;
  text-align: center;
  padding: 12px;
  text-decoration: none;
  font-size: 18px;
  line-height: 25px;
  border-radius: 4px;
}

.header a.logo {
  font-size: 25px;
  font-weight: bold;
}

.header a:hover {
  background-color: #ddd;
  color: black;
}

.header a.active {
  background-color: dodgerblue;
  color: white;
  border-radius: 1px;
}
footer {
    position: left;
    bottom: 0;
    width: 100%;
    background-color: rgba(255, 255, 255, 0.0);
    padding: 0px 0;
}

</style>
<div class="header">
    <a href="{% url 'sendmail:home' %}" class="logo">SendMailService</a>

    <div class="topnav">
        <a class="active" href="{% url 'sendmail:home' %}">На главную</a>

        {% if user.is_authenticated %}
        <a class="active" href="{% url 'users:logout' %}">Выйти</a>
        <a class="text text-muted" href="#profile" >{{ user.email }}</a>
        {% else %}
        <a href="{% url 'users:login' %}">Войти</a>
        <a href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </div>
</div>

<div id="myNav" class="overlay">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
    <div class="overlay-content">
        <a href="{% url 'sendmail:mailing_list' %}">Рассылки</a>
        <a href="{% url 'sendmail:message_list' %}">Сообщения</a>
        <a href="{% url 'sendmail:client_list' %}">Клиенты</a>
        {% if perms.sendmail.set_is_active %}
        <a href="{% url 'users:list_view' %}">Пользователи</a>
        {% endif %}
    </div>
</div>


<span style="font-size:30px;cursor:pointer" onclick="openNav()">☰ Открыть меню</span>

<script>
    function openNav() {
        document.getElementById("myNav").style.width = "100%";
    }

    function closeNav() {
        document.getElementById("myNav").style.width = "0%";
    }
</script>


{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SendMailService
            <small class="d-block mb-3 text-muted">&copy; 2023-{% now 'Y' %}</small>
        </div>
    </div>
</footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

users/templates/users/home.html
{% extends 'users/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h3 class="display-4">helpful matter</h3>
    <p class="lead">helpful matter
    </p>
</div>
<body>
<style>
    .card {
      max-width: 300px
    }
</style>
<div class="container">
    <div class="col-12">
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            <div class="col-4">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3 ">
                        <h4 class="my-0 fw-normal">helpful matter</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">text</h1>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">text</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">text</h1>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">text</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">text</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% block content %}
    <div class="col-12">
        <form class="form-signin" method="post">
            {% csrf_token %}
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Вход
                    </h3>
                </div>
                <div class="card-body">
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>

                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Регистрация
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/success_verify.html
{% extends 'users/base.html' %}

{% block content %}
<div class="row text-center">
    <div class="col-12">
        <h3>
            Поздравляем, Вы успешно зарегистрировались!<br>
            Для дальнейшей работы нажмите "Войти".
        </h3>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'users/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/users_list.html
{% extends 'users/base.html' %}
{% block content %}
    <div class="header mx-auto text-center">
        <h5 class="display-4">{{ title }}</h5>
    </div>
    <div class="col-12">
        <div class="row mb-3">
            {% for object in object_list %}
                <div class="col-6 mb-3">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="my-0 font-weight-normal mb-3">Пользователь: {{ object.email }}</h3>
                            {% if not object.is_active %}
                                <p>Заблокирован</p>
                            {% else %}
                                <p>Активный</p>
                            {% endif %}
                            <a class="p-2 btn btn-outline-primary" href="{% url 'users:edit' object.pk %}">Редактировать</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

users/templates/users/verify_message.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="row text-center">
        <div class="col-12">
            <h3>На почту, указанную при регистрации направлена ссылка.<br>
                Пожалуйста, перейдите по ней, чтобы завершить регистрацию.
            </h3>
        </div>
    </div>
{% endblock %}